## **Principal Component Analysis (PCA) Implementation from Scrach without using  Libraries**
**Why we use PCA in machine learning:**??

three main reason that i found are:

**Reduces training time** — due to smaller dataset

**Removes nois**e — by keeping only what’s relevant

**Makes visualization possibl**e — in cases where you have a maximum of 3 principal components

In [33]:
#Data samples
feature_A = [2.5, 0.5, 4, 6.5, 7 ,2.3 ,2,1, 1.5 ,1.1]
feature_B = [2.4,0.7,1,2.9, 2.2 ,3.0 ,2.7 ,1.6 ,1.1 ,1.6]
feature_C = [1.4, 2.1, 4.2, 1, 3.5, 6.2, 8.5,1.5,3.1,20]
len(feature_C)

10

# Step_1:
Finding mean and standard deviation of data samples 

In [34]:
#function to find sum
def sum_values(giveme):
  sum_i = 0
  for i in giveme:
    sum_i = sum_i + i;
  return sum_i

In [35]:
fa_sum = sum_values(feature_A)
print("sum of feature fA: %.2f" %fa_sum)
fb_sum = sum_values(feature_B)
print("sum of feature fB: %.2f" %fb_sum)
fc_sum = sum_values(feature_C)
print("sum of feature fC: %.2f" %fc_sum)

sum of feature fA: 28.40
sum of feature fB: 19.20
sum of feature fC: 51.50


In [36]:
#creating a function to find mean values
N = len(feature_A)
def mean_me (N, sum_val):
  mean_values = 0
  mean_values = sum_val / N
  return mean_values
  

In [37]:
#Finding mean values
fa_mean = mean_me(N,fa_sum)
print("mean of feature fA: %.2f" %fa_mean)
fb_mean = mean_me(N,fb_sum)
print("mean of feature fb: %.2f" %fb_mean)
fc_mean = mean_me(N,fc_sum)
print("mean of feature fc: %.2f" %fc_mean)

mean of feature fA: 2.84
mean of feature fb: 1.92
mean of feature fc: 5.15


In [38]:
fa_sum = sum_values(feature_A)
print("sum of featur fa: %.2f" %fa_sum)

sum of featur fa: 28.40


In [39]:
#Finding standard deviation
f_i = 0
std = 0
fi_sq = 0
def standard_deviation(N, fec, mean):
  fa_sq = 0
  for i in fec:
    f_i = (i - mean)
    fi_sq = (f_i * f_i)
    fa_sq += fi_sq
  std = (fa_sq / N )
  return std



In [40]:
fa_std_Dev = standard_deviation(N, feature_A, fa_mean)
print("std of Feature_a: %.2f" %fa_std_Dev)

fb_std_Dev = standard_deviation(N, feature_A, fb_mean)
print("std of Feature_b: %.2f" %fb_std_Dev)

fc_std_Dev = standard_deviation(N, feature_A, fc_mean)
print("std of Feature_c: %.2f" %fc_std_Dev)

std of Feature_a: 4.68
std of Feature_b: 5.53
std of Feature_c: 10.02


# **Feature Scaling**

Making all features to have mean = 0 and std_dev = 1

two techniques are used in ML

1: Normalization

# 2: Standardization

Formula:
stdise = (feature-mean) / std_Dev

In [41]:
def standardise_me(fec, mean, std):
  coef  = 0
  coef_sum = 0 
  temp= 0
  stdise = 0
  for i in fec:
    coef = i - mean
    #coef_sum +=  coef
  temp += (coef/ std)
  stdise += temp

  return stdise




In [42]:
stdise_fa = standardise_me(feature_A, fa_mean, fa_std_Dev)
print("standardise feature of fa: %.2f" %stdise_fa)

stdise_fb = standardise_me(feature_A, fa_mean, fb_std_Dev)
print("standardise feature of fb: %.2f" %stdise_fb)

stdise_fc = standardise_me(feature_A, fa_mean, fc_std_Dev)
print("standardise feature of fc: %.2f" %stdise_fc)

standardise feature of fa: -0.37
standardise feature of fb: -0.31
standardise feature of fc: -0.17


## **Step 3:**
# **Calculating Co-variance for all features,** 

ie finding the linear relationship between features

variance = (feature - mean)^2 / N

co-_rariance = ((f_a - mean_a)(feature_b - mean_b)) / N



In [44]:
#finding covariance first which is the spread of a data set around its mean value

def Co_variance (feature_1 , feature_2 , n, mean_1 , mean_2):
  temp1 = 0
  temp2 = 0
  corar = 0
  at_1 = 0
  at_2= 0


  for i in feature_1:
    at_1 = (i - mean_1)
    temp1 += at_1
  for j in feature_2:
    at_2 = (j - mean_2)
    temp2 += at_2

  covar = (temp1 * temp2) / (n - 1)

  return covar

In [45]:
print("Covariance of feature_A & feature_A is =" ,Co_variance(feature_A , feature_A , N, fa_mean , fa_mean))
print("Covariance of feature_A & feature_B is =" ,Co_variance(feature_A , feature_B , N, fa_mean , fb_mean))
print("Covariance of feature_A & feature_c is =" ,Co_variance(feature_A , feature_C , N, fa_mean , fc_mean))

print("Covariance of feature_B & feature_A is =" ,Co_variance(feature_B , feature_A , N, fb_mean , fa_mean))
print("Covariance of feature_B & feature_B is =" ,Co_variance(feature_B , feature_B , N, fb_mean , fb_mean))
print("Covariance of feature_B & feature_C is =" ,Co_variance(feature_B , feature_C , N, fb_mean , fc_mean))

print("Covariance of feature_C & feature_A is =" ,Co_variance(feature_C , feature_A , N, fc_mean , fa_mean))
print("Covariance of feature_C & feature_B is =" ,Co_variance(feature_C , feature_B , N, fc_mean , fb_mean))
print("Covariance of feature_C & feature_c is =" ,Co_variance(feature_C , feature_C , N, fc_mean , fc_mean))

Covariance of feature_A & feature_A is = 7.888609052210118e-31
Covariance of feature_A & feature_B is = 9.860761315262648e-31
Covariance of feature_A & feature_c is = 1.5777218104420236e-30
Covariance of feature_B & feature_A is = 9.860761315262648e-31
Covariance of feature_B & feature_B is = 1.232595164407831e-30
Covariance of feature_B & feature_C is = 1.9721522630525295e-30
Covariance of feature_C & feature_A is = 1.5777218104420236e-30
Covariance of feature_C & feature_B is = 1.9721522630525295e-30
Covariance of feature_C & feature_c is = 3.1554436208840472e-30


In [46]:
Cov_AA = Co_variance(feature_A , feature_A , N, fa_mean , fa_mean)
Cov_AB = Co_variance(feature_A , feature_B , N, fa_mean , fb_mean)
Cov_AC = Co_variance(feature_A , feature_C , N, fa_mean , fc_mean)

Cov_BA =Co_variance(feature_B , feature_A , N, fb_mean , fa_mean)
Cov_BB = Co_variance(feature_B , feature_B , N, fb_mean , fb_mean)
Cov_BC = Co_variance(feature_B , feature_C , N, fb_mean , fc_mean)

Cov_CA = Co_variance(feature_C , feature_A , N, fc_mean , fa_mean)
Cov_CB = Co_variance(feature_C , feature_B , N, fc_mean , fb_mean)
Cov_CC = Co_variance(feature_C , feature_C , N, fc_mean , fc_mean)

In [47]:
co_variance = [[Cov_AA],[Cov_AB],[Cov_AC], 
         [Cov_BA], [Cov_BB], [Cov_BC], 
         [Cov_CA], [Cov_CB], [Cov_CC]]
co_variance

[[7.888609052210118e-31],
 [9.860761315262648e-31],
 [1.5777218104420236e-30],
 [9.860761315262648e-31],
 [1.232595164407831e-30],
 [1.9721522630525295e-30],
 [1.5777218104420236e-30],
 [1.9721522630525295e-30],
 [3.1554436208840472e-30]]

# Creating Covariance Metrix

In [63]:
# Plot our data
import plotly.graph_objects as go
import numpy as np

data = np.stack((feature_A,feature_B,feature_C)).T 
print("data.shape =",data.shape)
#cov = np.cov(data.T)
cov = (feature_A , feature_B ,feature_C,  N, fa_mean , fb_mean, fc_mean)
print("covariance matrix =\n",cov)


fig = go.Figure(data=[go.Scatter3d(x=feature_A, y=feature_B, z=feature_C,mode='markers', marker=dict(size=8,opacity=0.5), name="data" )])
fig.update_layout( xaxis_title="A's Features", yaxis_title="B's Features", yaxis = dict(scaleanchor = "x",scaleratio = 1) )
fig.show()

data.shape = (10, 3)
covariance matrix =
 [[ 5.20488889e+00  8.20222222e-01 -3.83333333e+00]
 [ 8.20222222e-01  6.95111111e-01  1.22222222e-02]
 [-3.83333333e+00  1.22222222e-02  3.27316667e+01]]


Step_04:

## **Finding Components of PCA**

directions along which the data varies the most

To find Principal Components , we need to find eigenvalues and than

 eigenvectors for our covariance matrix.

 **Eigenvalues** = det(A−λI)= 0

 Eigenvectors = wait..

In [49]:
def zeros_matrix(rows, cols): #det(cov-hI) = [x1,x2,x3]
    M = []
    while len(M) < rows:
        M.append([])
        while len(M[-1]) < cols:
            M[-1].append(1)
 
    return M

## Creating N*N metric  

In [50]:
def n_matrix(rows, cols):
    M = []
    while len(M) < rows:
        M.append([])
        while len(M[-1]) < cols:
            M[-1].append(0)
 
    return M

In [51]:
#for lambdaa metrix
def lm_matrix(rows, cols):
    M = []
    while len(M) < rows:
        M.append([])
        while len(M[-1]) < cols:
            M[-1].append(1)
       

 
    return M
lambdaa = lm_matrix(3,1)
lambdaa
lambda_cros_I = [["x_1"], ["x_2"], ["x_3"],
                 [0], [0], [0],
                 [0], [0], [0]]

In [52]:
#for lambdaa metrix
def zero_matrix(rows, cols):
    M = []
    while len(M) < rows:
        M.append([])
        while len(M[-1]) < cols:
            M[-1].append(0)
 
    return M
results_i = zero_matrix(3,1)
results_i

[[0], [0], [0]]

In [53]:
d3_results = n_matrix(3,3)
d3_results

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]

Identity Metric

In [54]:
def identity_matrix(n):     #n: the square size of the matrix
    IdM = n_matrix(3, 3)
    for i in range(n):
        IdM[i][i] = 1
 
    return IdM

In [55]:
identity_m = identity_matrix(3)
identity_m

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]

In [56]:
#Function for multiplying (3*3) * (3*3) metrices
def matrix_multiplication(mat_1 , mat_2, results):
  for i in range(len(mat_1)):
    # iterating by column of mat_1
    for j in range(len((mat_2[0]))):
 
        # iterating by rows of mat_2
        for k in range(len((mat_2))):
            results[i][j] += mat_1[i][k] * mat_2[k][j]
    return results
 

In [57]:
lambda_cros_I = matrix_multiplication(identity_m ,lambdaa, results_i )

In [58]:
lambda_cros_I

[[1], [0], [0]]

In [59]:
# to find cov - lambda_1
